name: Claude Code Issue Creator

on:
  workflow_dispatch:
    inputs:
      issue_description:
        description: 'Brief description of the issue to create (e.g., "Add dark mode support")'
        required: true
        type: string
      priority:
        description: 'Issue priority level'
        required: false
        type: choice
        options:
          - low
          - medium
          - high
          - critical
        default: medium
      labels:
        description: 'Comma-separated labels (e.g., "enhancement,ui")'
        required: false
        type: string
        default: ''

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code to Generate Issue
        id: claude-issue
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"

          # Prompt to generate comprehensive issue
          direct_prompt: |
            Based on the following brief description, create a comprehensive GitHub issue:

            **Description**: ${{ inputs.issue_description }}
            **Priority**: ${{ inputs.priority }}

            IMPORTANT: Your response MUST start with the following format EXACTLY:

            TITLE: [Your clear, concise issue title here - max 80 characters]

            [Then the rest of the issue body below]

            Please analyze the codebase and create a detailed issue that includes:

            1. **Problem Statement**:
               - What problem does this solve?
               - Why is this needed?
               - Who benefits from this?

            2. **Proposed Solution**:
               - High-level approach
               - Key technical considerations
               - Affected files/components (reference actual files from the codebase)

            3. **Technical Details**:
               - Implementation steps
               - API/interface changes needed
               - Dependencies or prerequisites

            4. **Acceptance Criteria**:
               - Specific, testable requirements
               - Definition of done

            5. **Testing Strategy**:
               - Unit tests needed
               - Integration tests needed
               - Manual testing steps

            6. **Additional Context**:
               - Related issues or PRs (if any)
               - Documentation updates needed
               - Migration or breaking changes

            7. **Estimated Complexity**: (Small/Medium/Large/XL)

            Please explore the codebase to understand the current architecture and provide
            specific, actionable details. Reference actual file paths and existing patterns.

            REMEMBER: Start your response with "TITLE: " followed by the issue title, then a blank line, then the issue body.

          # Allow Claude to explore the codebase
          allowed_tools: "Read,Glob,Grep,Bash(git log),Bash(git grep)"

      - name: Extract Issue Title and Body
        id: extract
        run: |
          # Read the execution file and extract Claude's final text responses
          EXECUTION_FILE="${{ steps.claude-issue.outputs.execution_file }}"

          if [ ! -f "$EXECUTION_FILE" ]; then
            echo "Error: Execution file not found at $EXECUTION_FILE"
            exit 1
          fi

          # Extract all text content from assistant messages (excluding tool use)
          # We look for messages with role=assistant and type=text
          RESPONSE=$(jq -r '
            [.[] |
             select(.type == "assistant") |
             .message.content[] |
             select(.type == "text") |
             .text
            ] | join("\n\n")
          ' "$EXECUTION_FILE")

          # Debug: Show extracted response
          echo "=== Extracted Response ==="
          echo "$RESPONSE"
          echo "=========================="

          # Extract title - look for line starting with "TITLE: "
          TITLE=$(echo "$RESPONSE" | grep -i '^TITLE:' | head -n 1 | sed 's/^TITLE: *//i;s/^[ \t]*//;s/[ \t]*$//')

          # If title is still empty, try first non-empty line (fallback)
          if [ -z "$TITLE" ]; then
            TITLE=$(echo "$RESPONSE" | grep -v '^\s*$' | head -n 1 | sed 's/^[#* ]*//;s/^[ \t]*//;s/[ \t]*$//')
          fi

          # If title is still empty, use a default
          if [ -z "$TITLE" ]; then
            TITLE="Issue: ${{ inputs.issue_description }}"
          fi

          # Extract body - skip the TITLE line and any blank lines after it
          BODY=$(echo "$RESPONSE" | sed -n '/^TITLE:/,$p' | tail -n +2 | sed '/./,$!d')

          # Save to environment files for multiline content
          {
            echo 'ISSUE_TITLE<<EOF'
            echo "$TITLE"
            echo 'EOF'
          } >> "$GITHUB_ENV"

          {
            echo 'ISSUE_BODY<<EOF'
            echo "$BODY"
            echo ''
            echo '---'
            echo ''
            echo '_This issue was automatically generated by Claude Code based on the description:_ `${{ inputs.issue_description }}`'
            echo ''
            echo '_Priority:_ ${{ inputs.priority }}'
            echo 'EOF'
          } >> "$GITHUB_ENV"

          # Debug output
          echo "Extracted title: $TITLE"

      - name: Create GitHub Issue
        id: create-github-issue
        uses: actions/github-script@v7
        with:
          script: |
            const labels = '${{ inputs.labels }}'.split(',').map(l => l.trim()).filter(l => l);

            // Add priority label
            const priorityLabel = 'priority: ${{ inputs.priority }}';
            if (!labels.includes(priorityLabel)) {
              labels.push(priorityLabel);
            }

            // Add auto-generated label
            if (!labels.includes('auto-generated')) {
              labels.push('auto-generated');
            }

            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: process.env.ISSUE_TITLE,
              body: process.env.ISSUE_BODY,
              labels: labels
            });

            console.log(`Created issue #${issue.data.number}: ${issue.data.html_url}`);
            core.setOutput('issue_number', issue.data.number);
            core.setOutput('issue_url', issue.data.html_url);

      - name: Comment with Issue Link
        run: |
          echo "✅ Successfully created issue: ${{ steps.create-github-issue.outputs.issue_url }}"
