name: Claude Code Issue to PR

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to implement (e.g., 42)'
        required: true
        type: number
      branch_prefix:
        description: 'Branch name prefix (will create: prefix/issue-N)'
        required: false
        type: string
        default: 'feature'
      draft_pr:
        description: 'Create as draft PR?'
        required: false
        type: boolean
        default: false

jobs:
  implement-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper branching

      - name: Fetch Issue Details
        id: fetch-issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue_number }}
            });

            console.log(`Fetched issue #${issue.data.number}: ${issue.data.title}`);

            // Save to outputs
            core.setOutput('issue_title', issue.data.title);
            core.setOutput('issue_body', issue.data.body || '');
            core.setOutput('issue_url', issue.data.html_url);

            // Save to environment for multiline content
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `ISSUE_TITLE<<EOF\n${issue.data.title}\nEOF\n`);
            fs.appendFileSync(process.env.GITHUB_ENV, `ISSUE_BODY<<EOF\n${issue.data.body || ''}\nEOF\n`);

      - name: Run Claude Code to Implement Issue
        id: claude-implement
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"

          direct_prompt: |
            You are implementing GitHub issue #${{ inputs.issue_number }}.

            **Issue Title**: ${{ env.ISSUE_TITLE }}

            **Issue Description**:
            ${{ env.ISSUE_BODY }}

            **Your Task**:
            1. **Research Phase**: Explore the codebase to understand:
               - Current architecture and patterns
               - Files and components that need modification
               - Existing tests and testing patterns
               - Dependencies and constraints

            2. **Implementation Phase**:
               - Create a new branch: `${{ inputs.branch_prefix }}/issue-${{ inputs.issue_number }}`
               - Implement the solution following the issue requirements
               - Follow existing code patterns and conventions
               - Add or update tests as needed
               - Ensure code quality and best practices

            3. **Documentation Phase**:
               - Update relevant documentation
               - Add code comments where needed

            4. **Commit Phase**:
               - Create clear, descriptive commits
               - Reference the issue in commits (e.g., "Fixes #${{ inputs.issue_number }}")

            5. **PR Creation Phase**:
               - Push the branch to origin
               - Create a pull request with:
                 - Clear title referencing the issue
                 - Summary of changes made
                 - Testing instructions
                 - Any notes for reviewers
               ${{ inputs.draft_pr && '- Mark the PR as DRAFT' || '' }}

            **Important Guidelines**:
            - If the issue is unclear or missing details, document assumptions in the PR
            - If you encounter blockers, document them in the PR description
            - Write clean, maintainable code that matches the project's style
            - Ensure all tests pass before creating the PR

            **Success Criteria**:
            - Branch created and pushed
            - Code implements the issue requirements
            - Tests added/updated and passing
            - PR created with clear description

            Begin by exploring the codebase to understand what needs to be done!

          # Grant Claude the tools needed for full implementation
          allowed_tools: "Read,Write,Edit,Glob,Grep,Bash(git *),Bash(npm *),Bash(yarn *),Bash(pnpm *),Bash(python *),Bash(pytest),Bash(make *)"

      - name: Extract PR Information
        id: extract-pr
        run: |
          # Read the execution file
          EXECUTION_FILE="${{ steps.claude-implement.outputs.execution_file }}"

          if [ ! -f "$EXECUTION_FILE" ]; then
            echo "Error: Execution file not found at $EXECUTION_FILE"
            exit 1
          fi

          # Extract text responses from Claude
          RESPONSE=$(jq -r '
            [.[] |
             select(.type == "assistant") |
             .message.content[] |
             select(.type == "text") |
             .text
            ] | join("\n\n")
          ' "$EXECUTION_FILE")

          echo "=== Claude Response ==="
          echo "$RESPONSE"
          echo "======================="

          # Try to extract PR URL from response
          PR_URL=$(echo "$RESPONSE" | grep -oE 'https://github.com/[^/]+/[^/]+/pull/[0-9]+' | head -n 1)

          if [ -n "$PR_URL" ]; then
            echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
            echo "âœ… PR created: $PR_URL"
          else
            echo "âš ï¸  Could not extract PR URL from response"
            echo "pr_url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Comment on Original Issue
        if: steps.extract-pr.outputs.pr_url != ''
        uses: actions/github-script@v7
        with:
          script: |
            const prUrl = '${{ steps.extract-pr.outputs.pr_url }}';
            const prNumber = prUrl.split('/').pop();

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ inputs.issue_number }},
              body: `ðŸ¤– **Automated Implementation**\n\nI've created a pull request to address this issue: ${prUrl}\n\nPlease review the changes and provide feedback!`
            });

            console.log(`âœ… Commented on issue #${{ inputs.issue_number }} with PR link`);

      - name: Summary
        run: |
          echo "## ðŸŽ‰ Issue Implementation Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Issue**: #${{ inputs.issue_number }} - ${{ env.ISSUE_TITLE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Issue URL**: ${{ steps.fetch-issue.outputs.issue_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -n "${{ steps.extract-pr.outputs.pr_url }}" ]; then
            echo "**Pull Request**: ${{ steps.extract-pr.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "âœ… Successfully created PR from issue!" >> $GITHUB_STEP_SUMMARY
          else
            echo "âš ï¸  PR URL could not be extracted. Check the Claude Code execution logs." >> $GITHUB_STEP_SUMMARY
          fi
