name: Claude Code Issue to PR

on:
  # Method 1: Manual trigger with issue number or URL
  workflow_dispatch:
    inputs:
      issue_reference:
        description: 'Issue number (e.g., 42) OR full URL (e.g., https://github.com/owner/repo/issues/42)'
        required: true
        type: string
      branch_prefix:
        description: 'Branch name prefix (will create: prefix/issue-N)'
        required: false
        type: string
        default: 'feature'
      draft_pr:
        description: 'Create as draft PR?'
        required: false
        type: boolean
        default: false

  # Method 2: Comment trigger - comment "/implement" on any issue
  issue_comment:
    types: [created]

  # Method 3: Label trigger - add "auto-implement" label to any issue
  issues:
    types: [labeled]

jobs:
  # First, determine if we should run and extract issue number
  check-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      issue_number: ${{ steps.check.outputs.issue_number }}
      branch_prefix: ${{ steps.check.outputs.branch_prefix }}
      draft_pr: ${{ steps.check.outputs.draft_pr }}
      trigger_type: ${{ steps.check.outputs.trigger_type }}
    steps:
      - name: Check Trigger and Extract Issue Number
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            let shouldRun = false;
            let issueNumber = null;
            let branchPrefix = 'feature';
            let draftPr = false;
            let triggerType = '';

            // Method 1: workflow_dispatch
            if (context.eventName === 'workflow_dispatch') {
              triggerType = 'manual';
              const ref = '${{ inputs.issue_reference }}';

              // Extract issue number from URL or use direct number
              const urlMatch = ref.match(/\/issues\/(\d+)/);
              if (urlMatch) {
                issueNumber = parseInt(urlMatch[1]);
              } else {
                issueNumber = parseInt(ref);
              }

              branchPrefix = '${{ inputs.branch_prefix }}' || 'feature';
              draftPr = ${{ inputs.draft_pr }};
              shouldRun = !isNaN(issueNumber);

              console.log(`Manual trigger for issue #${issueNumber}`);
            }

            // Method 2: issue_comment with /implement
            else if (context.eventName === 'issue_comment') {
              triggerType = 'comment';
              const comment = context.payload.comment.body.toLowerCase().trim();
              const isPullRequest = context.payload.issue.pull_request != null;

              // Only run on issues (not PRs) with /implement command
              if (!isPullRequest && comment.includes('/implement')) {
                issueNumber = context.payload.issue.number;
                shouldRun = true;

                // Parse optional parameters from comment
                // e.g., "/implement branch:fix draft:true"
                const branchMatch = comment.match(/branch:(\w+)/);
                if (branchMatch) branchPrefix = branchMatch[1];

                const draftMatch = comment.match(/draft:(true|yes)/);
                if (draftMatch) draftPr = true;

                console.log(`Comment trigger (/implement) on issue #${issueNumber}`);

                // React to the comment to show it was received
                await github.rest.reactions.createForIssueComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: context.payload.comment.id,
                  content: 'rocket'
                });
              }
            }

            // Method 3: labeled with auto-implement
            else if (context.eventName === 'issues' && context.payload.action === 'labeled') {
              triggerType = 'label';
              const labelName = context.payload.label.name;

              if (labelName === 'auto-implement') {
                issueNumber = context.payload.issue.number;
                shouldRun = true;

                console.log(`Label trigger (auto-implement) on issue #${issueNumber}`);
              }
            }

            // Set outputs
            core.setOutput('should_run', shouldRun.toString());
            core.setOutput('issue_number', issueNumber ? issueNumber.toString() : '');
            core.setOutput('branch_prefix', branchPrefix);
            core.setOutput('draft_pr', draftPr.toString());
            core.setOutput('trigger_type', triggerType);

            if (!shouldRun) {
              console.log('Conditions not met, workflow will skip implementation');
            }

  implement-issue:
    needs: check-trigger
    if: needs.check-trigger.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper branching

      - name: Add Status Comment
        if: needs.check-trigger.outputs.trigger_type != 'manual'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.check-trigger.outputs.issue_number }},
              body: 'ðŸš€ **Implementation Started**\n\nClaude Code is now working on implementing this issue. I\'ll update you when the PR is ready!\n\n_Triggered by: ${{ needs.check-trigger.outputs.trigger_type }}_'
            });

      - name: Fetch Issue Details
        id: fetch-issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.check-trigger.outputs.issue_number }}
            });

            console.log(`Fetched issue #${issue.data.number}: ${issue.data.title}`);

            // Save to outputs
            core.setOutput('issue_title', issue.data.title);
            core.setOutput('issue_body', issue.data.body || '');
            core.setOutput('issue_url', issue.data.html_url);

            // Save to environment for multiline content
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `ISSUE_TITLE<<EOF\n${issue.data.title}\nEOF\n`);
            fs.appendFileSync(process.env.GITHUB_ENV, `ISSUE_BODY<<EOF\n${issue.data.body || ''}\nEOF\n`);

      - name: Run Claude Code to Implement Issue
        id: claude-implement
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          mode: agent

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          # model: "claude-opus-4-20250514"

          direct_prompt: |
            You are implementing GitHub issue #${{ needs.check-trigger.outputs.issue_number }}.

            **Issue Title**: ${{ env.ISSUE_TITLE }}

            **Issue Description**:
            ${{ env.ISSUE_BODY }}

            **Your Task**:
            1. **Research Phase**: Explore the codebase to understand:
               - Current architecture and patterns
               - Files and components that need modification
               - Existing tests and testing patterns
               - Dependencies and constraints

            2. **Implementation Phase**:
               - Create a new branch: `${{ needs.check-trigger.outputs.branch_prefix }}/issue-${{ needs.check-trigger.outputs.issue_number }}`
               - Implement the solution following the issue requirements
               - Follow existing code patterns and conventions
               - Add or update tests as needed
               - Ensure code quality and best practices

            3. **Documentation Phase**:
               - Update relevant documentation
               - Add code comments where needed

            4. **Commit Phase**:
               - Create clear, descriptive commits
               - Reference the issue in commits (e.g., "Fixes #${{ needs.check-trigger.outputs.issue_number }}")

            5. **PR Creation Phase**:
               - Push the branch to origin
               - Create a pull request with:
                 - Clear title referencing the issue
                 - Summary of changes made
                 - Testing instructions
                 - Any notes for reviewers
               ${{ needs.check-trigger.outputs.draft_pr == 'true' && '- Mark the PR as DRAFT' || '' }}

            **Important Guidelines**:
            - If the issue is unclear or missing details, document assumptions in the PR
            - If you encounter blockers, document them in the PR description
            - Write clean, maintainable code that matches the project's style
            - Ensure all tests pass before creating the PR

            **Success Criteria**:
            - Branch created and pushed
            - Code implements the issue requirements
            - Tests added/updated and passing
            - PR created with clear description

            Begin by exploring the codebase to understand what needs to be done!

          # Grant Claude the tools needed for full implementation
          allowed_tools: "Read,Write,Edit,Glob,Grep,Bash(git *),Bash(npm *),Bash(yarn *),Bash(pnpm *),Bash(python *),Bash(pytest),Bash(make *)"

      - name: Extract PR Information
        id: extract-pr
        run: |
          # Read the execution file
          EXECUTION_FILE="${{ steps.claude-implement.outputs.execution_file }}"

          if [ ! -f "$EXECUTION_FILE" ]; then
            echo "Error: Execution file not found at $EXECUTION_FILE"
            exit 1
          fi

          # Extract text responses from Claude
          RESPONSE=$(jq -r '
            [.[] |
             select(.type == "assistant") |
             .message.content[] |
             select(.type == "text") |
             .text
            ] | join("\n\n")
          ' "$EXECUTION_FILE")

          echo "=== Claude Response ==="
          echo "$RESPONSE"
          echo "======================="

          # Try to extract PR URL from response
          PR_URL=$(echo "$RESPONSE" | grep -oE 'https://github.com/[^/]+/[^/]+/pull/[0-9]+' | head -n 1)

          if [ -n "$PR_URL" ]; then
            echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
            echo "âœ… PR created: $PR_URL"
          else
            echo "âš ï¸  Could not extract PR URL from response"
            echo "pr_url=" >> "$GITHUB_OUTPUT"
          fi

      - name: Comment on Original Issue
        if: steps.extract-pr.outputs.pr_url != ''
        uses: actions/github-script@v7
        with:
          script: |
            const prUrl = '${{ steps.extract-pr.outputs.pr_url }}';
            const prNumber = prUrl.split('/').pop();
            const triggerType = '${{ needs.check-trigger.outputs.trigger_type }}';

            let triggerEmoji = 'ðŸ¤–';
            let triggerText = 'Automated Implementation';

            if (triggerType === 'comment') {
              triggerEmoji = 'ðŸ’¬';
              triggerText = 'Comment-Triggered Implementation';
            } else if (triggerType === 'label') {
              triggerEmoji = 'ðŸ·ï¸';
              triggerText = 'Label-Triggered Implementation';
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ needs.check-trigger.outputs.issue_number }},
              body: `${triggerEmoji} **${triggerText} Complete**\n\nI've created a pull request to address this issue: ${prUrl}\n\nPlease review the changes and provide feedback!`
            });

            console.log(`âœ… Commented on issue #${{ needs.check-trigger.outputs.issue_number }} with PR link`);

      - name: Handle Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const triggerType = '${{ needs.check-trigger.outputs.trigger_type }}';

            // Only comment on non-manual triggers
            if (triggerType !== 'manual') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: ${{ needs.check-trigger.outputs.issue_number }},
                body: 'âš ï¸ **Implementation Failed**\n\nThe automated implementation encountered an error. Please check the [workflow run logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.'
              });
            }

      - name: Summary
        if: always()
        run: |
          echo "## ðŸŽ‰ Issue Implementation Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger Type**: ${{ needs.check-trigger.outputs.trigger_type }}" >> $GITHUB_STEP_SUMMARY
          echo "**Issue**: #${{ needs.check-trigger.outputs.issue_number }} - ${{ env.ISSUE_TITLE }}" >> $GITHUB_STEP_SUMMARY
          echo "**Issue URL**: ${{ steps.fetch-issue.outputs.issue_url }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -n "${{ steps.extract-pr.outputs.pr_url }}" ]; then
            echo "**Pull Request**: ${{ steps.extract-pr.outputs.pr_url }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "âœ… Successfully created PR from issue!" >> $GITHUB_STEP_SUMMARY
          else
            echo "âš ï¸  PR URL could not be extracted. Check the Claude Code execution logs." >> $GITHUB_STEP_SUMMARY
          fi
